trigger:
- master
- exp/*
- vs*

jobs:
- job: CoreBootstrappedOnLinux
  displayName: "Build and test on Linux using bootstrapped .NET Core MSBuild"
  pool: 'Hosted Ubuntu 1604'
  steps:
  - bash: . 'eng/cibuild_bootstrapped_msbuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Core 2.1 Test Results
    inputs:
      testRunTitle: 'Linux .NET Core 2.1'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnLinux build logs'
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: './stage1/artifacts/log/Debug/'
      ArtifactName: 'CoreOnLinux stage1 logs'
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnLinux test logs'
    condition: always()
